### ISSUE TITLE
Debug log setting updates

### ISSUE THREAD

**Issue by jeffpaul** [Mather-Sophi/sp-debug-bar-for-sophi#19]
### Describe the bug

Unchecking the "Enable debug log" setting still appears to show the `Sophi Logs submenu under Tools as well as the link to `View Logs`.

### Steps to Reproduce

I think the changes here could be:
- [x] update copy for the setting from `Debug log` and `Enable debug log` to perhaps `Debug logging` and `Display verbose logging output from Sophi Authentication, Sophi API requests, and CMS publishing events`?
- [ ] move the `View Logs` link to after the setting toggle, perhaps as `Display verbose logging output from Sophi Authentication, Sophi API requests, and CMS publishing events (view logs)`? <-- perhaps only show the link when setting is active?
- [x] Tools > Sophi Logs should only be available when the debug setting is active
- [x] update Tools submenu and page name from `Sophi Logs` to `Sophi.io Logs`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
@jeffpaul RE
> move the View Logs link to after the setting toggle, perhaps as Display verbose logging output from Sophi Authentication, Sophi API requests, and CMS publishing events (view logs)? <-- perhaps only show the link when setting is active?

The "Display verbose logging..." is a checkbox label, which is a whole clickable entity. Putting a link inside will add confusion.
