### ISSUE TITLE
Debug Bar JS SyntaxError

### ISSUE THREAD

**Issue by jeffpaul** [Mather-Sophi/sp-debug-bar-for-sophi#21]
### Describe the bug

The `JavaScript` panel for Debug Bar currently shows a SyntaxError on a dist JS file in the debug bar plugin, would be good to see if that's something we can easily resolve?

### Steps to Reproduce

1. Enable Debug Bar
2. Click on Debug in adminbar
3. Click on JavaScript panel
4. See SyntaxError (screenshot below)

### Screenshots, screen recording, code snippet

![Screen Shot 2022-05-17 at 1 29 53 PM](https://user-images.githubusercontent.com/2818133/168885006-2177063e-153e-4056-a9f0-bd4dd046e127.png)

### Environment information

PHP 7.4.29, MySQL 5.5.5, Sophi 1.1.1-dev, Debug Bar 1.1.3, Debug Bar for Sophi 0.1.0, WordPress 5.9.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
From the Env info I see this comes from 0.1.0

Same as #9 
Fixed by #12

**Comment by jeffpaul** [comment]
@cadic odd, I could have sworn I caught that after pushing 0.2.0 to the test site but perhaps my testing was prior.  either way, closing this, thanks!
