### ISSUE TITLE
Sophi Debug records overflow horizontally

### ISSUE THREAD

**Issue by jeffpaul** [Mather-Sophi/sp-debug-bar-for-sophi#22]
### Describe the bug

Viewing the `Sophi` panel for Debug Bar causes some of the request/response data to overflow horizontally and cause heavy side scrolling to try and read all the data.  Perhaps we should stack the `Response` data below the `Request` data instead of side-by-side?

### Steps to Reproduce

1. Click Debug in adminbar
2. Click Sophi
3. See Sophi Auth request/response rows with lots of content

### Screenshots, screen recording, code snippet

Primary page load
![Screen Shot 2022-05-17 at 1 35 02 PM](https://user-images.githubusercontent.com/2818133/168885807-3eda647a-6566-4c58-8511-29fab33e8ba5.png)

Scrolling horizontally to see additional content
![Screen Shot 2022-05-17 at 1 35 14 PM](https://user-images.githubusercontent.com/2818133/168885818-66b8e81d-fe36-411e-835f-58b3c403dc50.png)

### Environment information

PHP 7.4.29, MySQL 5.5.5, Sophi 1.1.1-dev, Debug Bar 1.1.3, Debug Bar for Sophi 0.1.0, WordPress 5.9.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
This is related to #21
When the JSON Viewer script fails, it will keep all jsons on the page as is (meaning they will be plain text with no word-wrap)

The solution: add styles for the default json block (`<pre>` with word-wrap)
