### ISSUE TITLE
Discrepancy between WP.org and GH ZIP directories

### ISSUE THREAD

**Issue by jeffpaul** [Mather-Sophi/sp-debug-bar-for-sophi#28]
### Describe the bug

Downloading a release asset from GH and a similar ZIP from WP.org shows slightly different directory names.  Some concern here that if someone downloads from GH and then later goes to update things may get wonky in their WP site directories.

### Steps to Reproduce

Probably best to have the GH directory update to `debug-bar-for-sophi` to match the WP.org slug, not sure if there's a way to build that into the release/deploy action/workflows or just easier to change the repo name to match perhaps?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
The target zip filename mirrors the repository name. We could either update the repository name to `debug-bar-for-sophi` or change this setting for the **Upload release asset** step

https://github.com/10up/sophi-debug-bar/blob/94f4de40177e38de6356d35f6426c2abb0a9fb7b/.github/workflows/wordpress-plugin-deploy.yml#L33

**Comment by jeffpaul** [comment]
@cadic seems like easiest will be when I transfer the repo 10 /globeandmail/ to have them rename it to `debug-bar-for-sophi` and I'll double check links/references that need to be updated post-repo moving

**Comment by jeffpaul** [comment]
Going to go ahead and rename the repo now, before we transfer to the Sophi team.  Will probably wait until the repo is transferred before releasing 0.3.0 to ensure the release process happens cleanly once the repo is in the `globeandmail` org.

**Comment by jeffpaul** [comment]
Confirming this works as expected now with the 0.3.0 release.
